# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25b28088b538200b87bbbbd68c60ed95f2e39a71e11ea118d1ea8a67917747a2f7fb0926d533ee9835d9cd05f8d298cc5ed1d0a4f3455e98049b21b319b3436b

test:
  secret_key_base: 54666a094e8d4bba57189ab4bceaeb6ebbe1c3f7b70ca87fe167517c88d09f5316bb914ae2dc0f0f76bf267861bc86085ed8bcc88de04dbe59d2b043019d5312

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
